name: Run rest assured test cases once pushed


on:
  push:
    branches: ["master"]


    jobs:
      test:
        runs-on: windows-2019
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-java@v3
            with:
              distribution: "microsoft"
              java-version: '17'
              cache: maven
          - run: mvn clean test


